image: node:18.4

stages:
  - build
  - lint
  - test
  - deploy


#region Build

build-backend:
  stage: build
  cache:
    key:
      prefix: backend
      files:
        - server/package-lock.json
    paths:
      - server/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - server/node_modules/
  before_script:
    - cd server
  script:
    - npm install

build-frontend:
  stage: build
  cache:
    key:
      prefix: frontend
      files:
        - client/package-lock.json
    paths:
      - client/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - client/build/
      - client/node_modules/
  before_script:
    - cd client
    - npm install
  script:
    - npm run build

build-db-app:
  stage: build
  image: maven:3.8-openjdk-17
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
        - db_java/target
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - db_java/target
  before_script:
    - cd db_java
  script:
    - mvn compile

#endregion


#region Lint

lint-backend:
  stage: lint
  dependencies:
    - build-backend
  before_script:
    - cd server
  script:
    - npm run lint

lint-frontend:
  stage: lint
  dependencies:
    - build-frontend
  before_script:
    - cd client
  script:
    - npm run lint

#endregion


#region Test

test-backend:
  stage: test
  dependencies:
    - build-backend
  before_script:
    - cd server
  script:
    - npm run test

test-frontend:
  stage: test
  dependencies:
    - build-frontend
  before_script:
    - cd client
  script:
    - npm run test

test-db-app:
  image: maven:3.8-openjdk-17
  stage: test
  dependencies:
    - build-db-app
  before_script:
    - cd db_java
  script:
    - mvn test

#endregion


#region Deploy

deploy-azure:
  stage: deploy
  image:  mcr.microsoft.com/azure-cli
  dependencies:
    - build-backend
    - build-frontend
  only:
    - main
    - staging
  before_script:
    - "az login --allow-no-subscriptions --service-principal -u $AZURE_DEPLOY_APP_ID -p $AZURE_DEPLOY_PASSWORD --tenant $AZURE_DEPLOY_TENANT"
  script:
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings WEBSITE_RUN_FROM_PACKAGE=$AZURE_DEPLOY_WEBSITE_RUN_FROM_PACKAGE"
    # Mongo
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings MONGO_CONNECTION_URI=$MONGO_CONNECTION_URI"
    # IGDB
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings IGDB_ID=$IGDB_ID"
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings IGDB_AUTH=$IGDB_AUTH"
    # Authentication
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings STEAM_API_KEY=$STEAM_API_KEY"
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings SECRET=$SECRET"
    # Redirects
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings HOST_URL=$HOST_URL"
    - "az webapp config appsettings set --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --settings REDIRECT_URL=$HOST_URL"
    # Deploy
    - zip -r deploy.zip server client/build package.json -x "__tests__"
    - "az webapp deployment source config-zip --resource-group $AZURE_DEPLOY_RESOURCE_GROUP --name $AZURE_DEPLOY_APP_NAME --src deploy.zip"

#endregion

